version: "3"
services:
  quiz-api:
    container_name: AWS_TEST
    restart: always
    build: .
    ports:
      - "4000:80"
    volumes:
      - ./src:/app/src
      # - /app/node_modules
      # - .:/app
    # volumes:
    #   - .:/app
